<?php
/** @var Alma\MonthlyPayments\Block\Adminhtml\System\SOCBlockLegal $block */
$position = $block->escapeHtml($block->getPosition());
?>
<div style="margin-left: 10px">
    <div><strong><?= $block->escapeHtml($block->getBlockTitle()) ?></strong></div>
    <div><?= $block->escapeHtml($block->getDescription()) ?></div>
    <div>
        <div id="alma_soc_detail_title_<?=$block->escapeHtmlAttr($position)?>" class="alma_collapse">
            <u><?= $block->escapeHtml($block->getDetailTitle()) ?></u>
        </div>
        <div id="alma_soc_detail_content_<?=$block->escapeHtmlAttr($position)?>">
            <ul>
                <?php foreach ($block->getDetailsArgs() as $arg): ?>
                    <li>
                        <?= $block->escapeHtml($arg) ?>
                    </li>
                <?php endforeach; ?>
            </ul>
        </div>
    </div>
    <?php if ($block->hasLink()): ?>
        <a href="<?= $block->escapeUrl($block->getConfigPageUrl()) ?>">
            <?= $block->escapeHtml($block->getLinkTitle()) ?>
        </a>
    <?php endif; ?>
</div>

<script>
    require([
        'jquery'
    ], function(jQuery){
        var isOpen = false;
        jQuery('#alma_soc_detail_title_<?=$block->escapeHtmlAttr($position)?>').click(function () {
            if (isOpen) {
                jQuery('#alma_soc_detail_title_<?=$block->escapeHtmlAttr($position)?>').removeClass('open');
                jQuery('#alma_soc_detail_content_<?=$block->escapeHtmlAttr($position)?>').hide();
                isOpen = false;
            } else {
                jQuery('#alma_soc_detail_title_<?=$block->escapeHtmlAttr($position)?>').addClass('open');
                jQuery('#alma_soc_detail_content_<?=$block->escapeHtmlAttr($position)?>').show();
                isOpen = true;
            }
        });

    });
</script>
