<?php
/** @var Alma\MonthlyPayments\Block\Adminhtml\System\SOCBlockLegal $block */
/** @var $escaper \Magento\Framework\Escaper */
$position = $block->getPosition()
?>
<div style="margin-left: 10px">
    <div><strong><?= $escaper->escapeHtml($block->getBlockTitle()) ?></strong></div>
    <div>
        <?= $escaper->escapeHtml($block->getDescriptionFirstPart()) ?>
        <a href="mailto:<?= $escaper->escapeHtmlAttr($block->getOptOutEmail()) ?>" target="_blank">
            <?= $escaper->escapeHtml($block->getOptOutLinkText()) ?>
        </a>
        <?= $escaper->escapeHtml($block->getDescriptionLastPart()) ?>
    </div>
    <div>
        <div id="alma_soc_detail_title_<?= $escaper->escapeHtmlAttr($position) ?>" class="alma_collapse">
            <u><?= $escaper->escapeHtml($block->getDetailTitle()) ?></u>
        </div>
        <div id="alma_soc_detail_content_<?= $escaper->escapeHtmlAttr($position) ?>">
            <ul>
                <?php foreach ($block->getDetailsArgs() as $arg): ?>
                    <li>
                        <?= $escaper->escapeHtml($arg) ?>
                    </li>
                <?php endforeach; ?>
            </ul>
        </div>
    </div>
    <?php if ($block->hasLink()): ?>
        <a href="<?= $escaper->escapeUrl($block->getConfigPageUrl()) ?>">
            <?= $escaper->escapeHtml($block->getLinkTitle()) ?>
        </a>
    <?php endif; ?>
</div>

<script>
    require([
        'jquery'
    ], function (jQuery) {
        var isOpen = false;
        jQuery('#alma_soc_detail_title_<?= $escaper->escapeJs($position) ?>').click(function () {
            if (isOpen) {
                jQuery('#alma_soc_detail_title_<?= $escaper->escapeJs($position) ?>').removeClass('open');
                jQuery('#alma_soc_detail_content_<?= $escaper->escapeJs($position) ?>').hide();
                isOpen = false;
            } else {
                jQuery('#alma_soc_detail_title_<?= $escaper->escapeJs($position) ?>').addClass('open');
                jQuery('#alma_soc_detail_content_<?= $escaper->escapeJs($position) ?>').show();
                isOpen = true;
            }
        });

    });
</script>
