<?php
/** @var $block \Alma\MonthlyPayments\Block\Catalog\Product\Insurance */
    $widgetIsActivated = $block->isActivatedWidgetInProductPage();
    $popupIsActivated = $block->isActivatedPopupInProductPage();

?>
<?php if ($widgetIsActivated) { ?>
<script type="module" src="<?= $block->getScriptUrl()?>"></script>
    <iframe id="product-alma-iframe" class="alma-insurance-iframe" width="100%" height="100%" src="<?= $block->getIframeUrl()?>"></iframe>
    <input type="hidden" name="alma_insurance_id" form="product_addtocart_form" value="">
    <input type="hidden" name="alma_insurance_name" form="product_addtocart_form" value="">
    <input type="hidden" name="alma_insurance_price" form="product_addtocart_form" value="">
    <div id="alma-insurance-modal"></div>
<?php } ?>
<?php if ($widgetIsActivated) { ?>
    <script>
        require([
            'jquery',
            'Magento_Customer/js/customer-data',
            'Alma_MonthlyPayments/js/model/front-price-calculation'
        ], function (
            $,
            customerData,
            utils
        ) {
            var cart = customerData.get('cart');
            var count = cart().summary_count;
            cart.subscribe(function () {
                if (cart().summary_count !== count) {
                    resetInsurance();
                }
            });
            var madeChoiceForInsurance = false;
            var isAddToCartFlow = false;
            let selectedAlmaInsurance = null
            window.addEventListener('message', (e) => {
                if(e.data.type === 'getResetInsuranceData'){
                    $('input[name=alma_insurance_id]').val('');
                    $('input[name=alma_insurance_name]').val('');
                    $('input[name=alma_insurance_price]').val('')
                    isAddToCartFlow = false;
                    madeChoiceForInsurance = false;
                }

                if (e.data.type === 'getSelectedInsuranceData') {
                    madeChoiceForInsurance = true;
                    selectedAlmaInsurance = e.data.selectedInsuranceData
                    if (selectedAlmaInsurance) {
                        $('input[name=alma_insurance_id]').val(selectedAlmaInsurance.option.id);
                        $('input[name=alma_insurance_name]').val(selectedAlmaInsurance.name);
                        $('input[name=alma_insurance_price]').val(selectedAlmaInsurance.option.price);
                    } else {
                        $('input[name=alma_insurance_id]').val('');
                        $('input[name=alma_insurance_name]').val('');
                        $('input[name=alma_insurance_price]').val('');
                    }
                    if(isAddToCartFlow){
                        document.getElementById('product-addtocart-button').click()
                    }
                    madeChoiceForInsurance = true;
                }
            })

            function sendDataToWidget() {
                console.log('<?= $block->getBaseProductSku() ?>')
                console.log('<?= $block->getMerchantId() ?>')
                console.log(getProductRegularPrice())
                getproductDataForApiCall('<?= $block->getBaseProductSku() ?>', '<?= $block->getMerchantId() ?>', getProductRegularPrice())
            }

            function getProductRegularPrice() {
                var regularPrice =  <?= $block->getProductPriceInCent() ?>;
                const productId = <?= $block->getBaseProductId() ?>;

                const productPriceBlock = $('#product-price-' +productId +' .price');
                if (productPriceBlock.length){
                    regularPrice = utils.convertHtmlPriceToCent(productPriceBlock.html())
                }

                const regularPriceBlock = $('#old-price-' +productId +' .price');
                if (regularPriceBlock.length){
                    regularPrice = utils.convertHtmlPriceToCent(regularPriceBlock.html())
                }
                return regularPrice.toString();
            }


            <?php if ($popupIsActivated) { ?>
            document.getElementById('product-addtocart-button').addEventListener('click', function (e) {
                if (!madeChoiceForInsurance){
                    e.preventDefault();
                    //sendDataToWidget()
                    openModal('popupModal');
                    madeChoiceForInsurance = true;
                    isAddToCartFlow = true;
                }
            })
            <?php } ?>
        });
    </script>
<?php } ?>
