<?php
/** @var $block \Alma\MonthlyPayments\Block\Catalog\Product\Insurance */
    $widgetIsActivated = $block->isActivatedWidgetInProductPage();
    $popupIsActivated = $block->isActivatedPopupInProductPage();

?>
<?php if ($widgetIsActivated) { ?>
<script type="module" src="<?= $block->getScriptUrl()?>"></script>
    <iframe title="Product alma Iframe" id="product-alma-iframe" class="alma-insurance-iframe" scrolling="no" src="<?= $block->getIframeUrl()?>"></iframe>
    <input type="hidden" name="alma_insurance_id" form="product_addtocart_form" value="">
    <input type="hidden" name="alma_insurance_name" form="product_addtocart_form" value="">
    <input type="hidden" name="alma_insurance_duration" form="product_addtocart_form" value="">
    <div id="alma-insurance-modal"></div>
<?php } ?>
<?php if ($widgetIsActivated) { ?>
    <script>
        require([
            'jquery',
            'Magento_Customer/js/customer-data',
            'Alma_MonthlyPayments/js/model/front-price-calculation'
        ], function (
            $,
            customerData,
            utils
        ) {
            utils.setSkuForWifget('<?= $block->getBaseProductSku() ?>')
            var cart = customerData.get('cart');
            var baseCount = 0;
            cart.subscribe(function () {
                if (cart().summary_count > baseCount) {
                    resetInsurance();
                    baseCount = cart().summary_count;
                }
                baseCount = cart().summary_count;
            });
            var madeChoiceForInsurance = false;
            var isAddToCartFlow = false;
            var selectedAlmaInsurance = null
            window.addEventListener('message', (e) => {
                if(e.data.type === 'almaEligibilityAnswer'){
                    let insuranceData = e.data.eligibilityCallResult
                    if (insuranceData) {
                        let height = e.data.widgetSize.height + 55
                        let iframe = document.getElementById('product-alma-iframe')
                        iframe.style.height = height + 'px'
                    }
                }

                if(e.data.type === 'getResetInsuranceData'){
                    $('input[name=alma_insurance_id]').val('');
                    $('input[name=alma_insurance_name]').val('');
                    $('input[name=alma_insurance_duration]').val('')
                    isAddToCartFlow = false;
                    madeChoiceForInsurance = false;
                }

                if (e.data.type === 'getSelectedInsuranceData') {
                    madeChoiceForInsurance = true;
                    selectedAlmaInsurance = e.data.selectedInsuranceData
                    if (selectedAlmaInsurance) {
                        $('input[name=alma_insurance_id]').val(selectedAlmaInsurance.insuranceContractId);
                        $('input[name=alma_insurance_name]').val(selectedAlmaInsurance.name);
                        $('input[name=alma_insurance_duration]').val(selectedAlmaInsurance.duration);
                    } else {
                        $('input[name=alma_insurance_id]').val('');
                        $('input[name=alma_insurance_name]').val('');
                        $('input[name=alma_insurance_duration]').val('');
                    }
                    if(isAddToCartFlow){
                        document.getElementById('product-addtocart-button').click()
                    }
                    madeChoiceForInsurance = true;
                }
            })


            var qtyNode = document.getElementById('qty');
            qtyNode.addEventListener('input',function (e) {
                var qty = e.target.value;
                if(qty > 0){
                    utils.refreshWidget(
                        '<?= $block->getProductPriceInCent() ?>',
                        '<?= $block->getBaseProductId() ?>',
                        '<?= $block->getMerchantId()?>',
                        '<?= $block->getQuoteId()?>',
                        '<?= $block->getCustomerSessionId()?>'
                    );
                }
            });

            <?php if ($popupIsActivated) { ?>
            document.getElementById('product-addtocart-button').addEventListener('click', function (e) {
                if (!madeChoiceForInsurance){
                    e.preventDefault();
                    openModal('popupModal', document.getElementById('qty').value);
                    madeChoiceForInsurance = true;
                    isAddToCartFlow = true;
                }
            })
            <?php } ?>
        });
    </script>
<?php } ?>
