<?php
/**
 * 2018 Alma / Nabla SAS
 *
 * THE MIT LICENSE
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated
 * documentation files (the "Software"), to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and
 * to permit persons to whom the Software is furnished to do so, subject to the following conditions:
 * The above copyright notice and this permission notice shall be included in all copies or substantial portions of the
 * Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *
 * @author    Alma / Nabla SAS <contact@getalma.eu>
 * @copyright 2018 Alma / Nabla SAS
 * @license   https://opensource.org/licenses/MIT The MIT License
 *
 */
/**
 * @see \Alma\MonthlyPayments\Block\Catalog\Product\View
 */

/** @var $block \Alma\MonthlyPayments\Block\Catalog\Product\View */
/** @var $escaper \Magento\Framework\Escaper */
/** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */

$config = $block->getConfig();
$widgetConfig = $block->getWidgetConfig();
$hasCustomPosition = $widgetConfig->isCustomWidgetPosition();
$customSelector = $widgetConfig->getWidgetContainerSelector();
$containerId = 'alma-widget';
if ($widgetConfig->showProductWidget() && $block->getJsonPlans() && $block->getPrice()>0):?>
    <div id=<?= $block->escapeHtml($containerId) ?> ></div>
    <script type="text/x-magento-init">
        {
            "#<?= $block->escapeHtml($containerId) ?>": {
                "Alma_MonthlyPayments/js/view/catalog/badge": {
                    "customDisplay" : {
                        "hasCustomPosition" : <?= $block->escapeHtml($hasCustomPosition) ?>,
                        "customContainerSelector" :"<?= $block->escapeHtml($customSelector) ?>",
                        "isPrepend" : <?= $block->escapeHtml($widgetConfig->prependWidgetInContainer()) ?>
                        },
                    "containerId" : "<?= $block->escapeHtml($containerId) ?>",
                    "productPrice" : <?= $block->escapeHtml($block->getPrice()) ?>,
                    "useQuantityForWidgetPrice": <?= $block->escapeHtml($widgetConfig->useQuantityForWidgetPrice()) ?>,
                    "productId": <?= $block->escapeHtml($block->getProductId()) ?>,
                    "merchantId": "<?= $block->escapeHtml($config->getMerchantId()) ?>",
                    "activeMode": "<?= $block->escapeHtml($block->getActiveMode()) ?>",
                    "locale": "<?= $block->escapeHtml($block->getLocale()) ?>",
                    "jsonPlans": <?= $block->escapeHtml($block->getJsonPlans()) ?>
                }
            }
        }
    </script>

<?php endif; ?>
