<?php
/**
 * 2018 Alma / Nabla SAS
 *
 * THE MIT LICENSE
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated
 * documentation files (the "Software"), to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and
 * to permit persons to whom the Software is furnished to do so, subject to the following conditions:
 * The above copyright notice and this permission notice shall be included in all copies or substantial portions of the
 * Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *
 * @author    Alma / Nabla SAS <contact@getalma.eu>
 * @copyright 2018 Alma / Nabla SAS
 * @license   https://opensource.org/licenses/MIT The MIT License
 *
 */
/**
 * @see \Alma\MonthlyPayments\Block\Catalog\Product\View
 */

/** @var $block \Alma\MonthlyPayments\Block\Catalog\Product\View */
/** @var $escaper \Magento\Framework\Escaper */
/** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */

$config = $block->getConfig();
$widgetConfig = $block->getWidgetConfig();
$containerId = 'alma-widget';
if ($widgetConfig->showProductWidget() && $block->getJsonPlans() && $block->getPrice() > 0): ?>
    <div id="<?= $escaper->escapeHtmlAttr($containerId) ?>"></div>
    <script type="text/x-magento-init">
        {
            "#<?= $escaper->escapeJs($containerId) ?>": {
                "Alma_MonthlyPayments/js/view/catalog/badge": {
                    "customDisplay" : {
                        "hasCustomPosition" : <?= $escaper->escapeJs($widgetConfig->isCustomWidgetPosition()) ?>,
                        "customContainerSelector" : "<?= $escaper->escapeJs($widgetConfig->getWidgetContainerSelector()) ?>",
                        "isPrepend" : <?= $widgetConfig->prependWidgetInContainer() ? 'true' : 'false' ?>
        },
    "containerId" : "<?= $escaper->escapeJs($containerId) ?>",
                    "productPrice" : <?= (float)$block->getPrice() ?>,
                    "useQuantityForWidgetPrice": <?= $widgetConfig->useQuantityForWidgetPrice() ? 'true' : 'false' ?>,
                    "productId": <?= (int)$block->getProductId() ?>,
                    "merchantId": "<?= $escaper->escapeJs($config->getMerchantId()) ?>",
                    "activeMode": "<?= $escaper->escapeJs($block->getActiveMode()) ?>",
                    "locale": "<?= $escaper->escapeJs($block->getLocale()) ?>",
                    "jsonPlans": <?= /* @noEscape */
                    $block->getJsonPlans() ?>
        }
    }
}
    </script>

<?php endif; ?>
