<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

use Alma\MonthlyPayments\Helpers\PaymentPlansHelper;

?>

<?php
/**
 * @see \Alma\MonthlyPayments\Block\Adminhtml\System\Config\FeePlansConfigFrontModel
 */
/** @var $block \Alma\MonthlyPayments\Block\Adminhtml\System\Config\FeePlansConfigFrontModel */
/** @var $escaper \Magento\Framework\Escaper */
$_htmlId = $block->getHtmlId() ? $block->getHtmlId() : '_' . uniqid();
$_colspan = $block->isAddAfter() ? 2 : 1;
?>

<div class="design_theme_ua_regexp" id="grid<?= $escaper->escapeHtmlAttr($_htmlId) ?>">
    <div class="admin__control-table-wrapper">
        <table class="admin__control-table" id="<?= $escaper->escapeHtmlAttr($block->getElement()->getId()) ?>">
            <thead>
            <tr>
                <?php foreach ($block->getColumns() as $columnName => $column): ?>
                    <th><?= $escaper->escapeHtml($column['label']) ?></th>
                <?php endforeach; ?>
            </tr>
            </thead>
            <tbody id="addRow<?= $escaper->escapeHtmlAttr($_htmlId) ?>"></tbody>
        </table>
    </div>
    <input type="hidden" name="<?= $escaper->escapeHtmlAttr($block->getElement()->getName()) ?>[__empty]" value=""/>

    <script>
        require([
            'mage/template',
            'prototype'
        ], function (mageTemplate) {
            // create row creator
            window.arrayRow<?= $escaper->escapeJs($_htmlId) ?> = {

                // define row prototypeJS template
                template: mageTemplate(
                    '<tr id="<%- _id %>">'
                    <?php foreach ($block->getColumns() as $columnName => $column): ?>
                    + '<td>'
                    + '<?= $escaper->escapeJs($block->renderCellTemplate($columnName)) ?>'
                    + '<\/td>'
                    <?php endforeach; ?>

                    <?php if ($block->isAddAfter()): ?>
                    + '<td><button class="action-add" type="button" id="addAfterBtn<%- _id %>"><span>'
                    + '<?= $escaper->escapeJs($escaper->escapeHtml(__('Add after'))) ?>'
                    + '<\/span><\/button><\/td>'
                    <?php endif; ?>

                    + '<\/tr>'
                ),

                add: function (rowData, insertAfterId) {
                    // generate default template data
                    var templateValues;

                    // Prepare template values
                    if (rowData) {
                        templateValues = rowData;
                    } else {
                        var d = new Date();
                        templateValues = {
                            <?php foreach ($block->getColumns() as $columnName => $column): ?>
                                <?= $escaper->escapeJs($columnName) ?>: '',
                            <?php endforeach; ?>
                            'option_extra_attrs': {},
                            _id: '_' + d.getTime() + '_' + d.getMilliseconds()
                        };
                    }

                    // Insert new row after specified row or at the bottom
                    if (insertAfterId) {
                        Element.insert($(insertAfterId), {after: this.template(templateValues)});
                    } else {
                        Element.insert($('addRow<?= $escaper->escapeJs($_htmlId) ?>'), {bottom: this.template(templateValues)});
                    }

                    // Fill controls with data
                    if (rowData) {
                        var rowInputElementNames = Object.keys(rowData.column_values);
                        for (var i = 0; i < rowInputElementNames.length; i++) {
                            if ($(rowInputElementNames[i])) {
                                $(rowInputElementNames[i]).setValue(rowData.column_values[rowInputElementNames[i]]);

                                if ($(rowInputElementNames[i]).id === "<?= $escaper->escapeJs(PaymentPlansHelper::PAY_NOW_KEY) ?>_<?= $escaper->escapeJs(PaymentPlansHelper::CUSTOM_MIN_PURCHASE_KEY) ?>") {
                                    $(rowInputElementNames[i]).setAttribute("readonly", true)
                                }
                            }
                        }
                    }

                },

                del: function (rowId) {
                    $(rowId).remove();
                }
            }

            // add existing rows
            <?php
            foreach ($block->getArrayRows() as $_rowId => $_row) {
                echo /** @noEscape */
                    "arrayRow" . $escaper->escapeJs($_htmlId) . ".add(" . /** @noEscape */
                    $_row->toJson() . ");\n";
            }
            ?>

            // Toggle the grid availability, if element is disabled (depending on scope)
            <?php if ($block->getElement()->getDisabled()): ?>
            toggleValueElements({checked: true}, $('grid<?= $escaper->escapeJs($_htmlId) ?>').parentNode);
            <?php endif; ?>
        });
    </script>
</div>
