<?php
/**
 * @var $block \Alma\MonthlyPayments\Block\Adminhtml\Insurance\SubscriptionDetails
 */
?>
<div>
    <iframe
        title="Alma Subscription Details"
        id="subscription-alma-iframe"
        class="subscription-alma-iframe"
        width="100%"
        height="100%"
        src="<?= $block->getOrderDetailsUrl() ?>">
    </iframe>
    <div id="alma-insurance-modal"></div>
</div>

<script data-cfasync="false" type="module" src="<?= $block->getScriptUrl() ?>"></script>
<script type="text/x-magento-init">
    {
        "*": {
            "Alma_MonthlyPayments/js/subscription_details":{
                "orderId": <?= $block->getOrderId() ?>,
                "incrementId": "<?= $block->getIncrementId() ?>",
                "mode": "<?= $block->getActiveMode() ?>",
                "orderDate": "<?= $block->getOrderDate() ?>",
                "firstName": "<?= $block->getCustomerFirstName() ?>",
                "lastName": "<?= $block->getCustomerLastName() ?>",
                "subscriptions": <?=  json_encode($block->getSubscriptionCollection(), true) ?>,
                "controllerCancelUrl": "<?= $block->getControllerCancelUrl() ?>"
            }
        }
    }
</script>
