<?php
/**
 * @var $block \Alma\MonthlyPayments\Block\Adminhtml\Insurance\SubscriptionDetails
 */
?>
<div>
    <iframe
        title="Alma Subscription Details"
        id="subscription-alma-iframe"
        class="subscription-alma-iframe"
        width="100%"
        height="100%"
        src="<?= $block->escapeHtml($block->getOrderDetailsUrl()) ?>">
    </iframe>
    <div id="alma-insurance-modal"></div>
</div>

<script data-cfasync="false" type="module" src="<?= $block->escapeUrl($block->getScriptUrl())?>"></script>
<script type="text/x-magento-init">
    {
        "*": {
            "Alma_MonthlyPayments/js/subscription_details":{
                "orderId": <?= $block->escapeHtml($block->getOrderId()) ?>,
                "incrementId": "<?= $block->escapeHtml($block->getIncrementId()) ?>",
                "mode": "<?= $block->escapeHtml($block->getActiveMode()) ?>",
                "orderDate": "<?= $block->escapeHtml($block->getOrderDate()) ?>",
                "firstName": "<?= $block->escapeHtml($block->getCustomerFirstName()) ?>",
                "lastName": "<?= $block->escapeHtml($block->getCustomerLastName()) ?>",
                "subscriptions": <?=  $block->escapeHtml(json_encode($block->getSubscriptionCollection(), true)) ?>,
                "controllerCancelUrl": "<?= $block->escapeUrl($block->getControllerCancelUrl()) ?>"
            }
        }
    }
</script>
