#!/usr/bin/env bash
set -Eeo pipefail
echo "Sourcing MAGENTO environments variables for php requirements"
source /var/www/env
[[ -n "$MAGENTO_PHP_REQUIREMENTS" ]]


# shellcheck disable=SC2086
echo "Installing apt-requirements: '$MAGENTO_PHP_REQUIREMENTS'" \
    && apt-get update \
    && apt-get install -y $MAGENTO_PHP_REQUIREMENTS

echo "Installing docker-php-ext requirements" \
    && docker-php-ext-install pdo_mysql \
    && docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ \
    && docker-php-ext-install gd \
    && docker-php-ext-install mbstring \
    && docker-php-ext-install zip \
    && docker-php-ext-install intl \
    && docker-php-ext-install xsl \
    && docker-php-ext-install soap \
    && docker-php-ext-install sockets \
    && docker-php-ext-install bcmath

if [[ x$MAGENTO_DEBUG == 'xyes' ]] ; then
    echo "Installing pecl xdebug"
    (yes '' || true) | pecl install xdebug
fi

echo "Installing pecl mcrypt"
(yes '' || true) | pecl install mcrypt-1.0.3 \
    && echo 'extension=mcrypt.so' > /usr/local/etc/php/conf.d/mcrypt.ini
