<?php
/**
 * @see \Alma\MonthlyPayments\Block\Adminhtml\System\Config\Collect
 */
/** @var $block \Alma\MonthlyPayments\Block\Adminhtml\System\Config\Collect */
/** @var $escaper \Magento\Framework\Escaper */

// Escaper compatibility for Adobe Commerce 2.3
if (!isset($escaper)) {
    $escaper = $block;
}
?>


<script>
    require([
        'jquery',
        'prototype'
    ], function (jQuery) {

        jQuery('#collect_button').click(function () {
            var data = {
                'form_key': window.FORM_KEY
            };
            jQuery.ajax({
                url: '<?= $escaper->escapeJs($block->getAjaxUrl()) ?>',
                data: data,
                showLoader: true,
                success: function (response) {
                    var lines = response.trim().split('\n').slice(-100);
                    var element = document.createElement('a');
                    element.setAttribute('href', 'data:text/plain;charset=utf-8,' + encodeURIComponent(lines.join('\n')));
                    element.setAttribute('download', 'alma' + Date.now() + '.log');
                    element.click();
                }
            });
            return true;
        });

    });
</script>

<?= /* @noEscape */
$block->getButtonHtml() ?>
