<?php
/**
 * @var $block \Alma\MonthlyPayments\Block\Adminhtml\Insurance\OrderViewMessage
 */

?>
<?php if ($block->hasActiveInsurance()): ?>
    <div class="message-alma warning">
        <b>
            <?=
                $block->escapeHtml(
                    __('Remember to cancel insurance subscriptions before initiating a refund')
                )
            ?>
        </b>
        <br/>
        <?= $block->escapeHtml(
            sprintf(
                __(
                    'This order includes one or more insurance subscriptions. Make sure that the subscription(s) is ' .
                    'canceled before proceeding with the refund. <a href=%s>Manage the cancellation directly here.</a>'
                ),
                $block->getOrderDetailsLink()
            )
        ) ?>

    </div>
<?php endif; ?>
